name: Deploy to GCP K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app to GCP VM with k3s
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_HOST }} << 'EOF'
          git clone https://github.com/mkputra/lacak-devops-test.git ~/app-deployment
          cd ~/app-deployment
          git pull origin main
          sudo kubectl apply -f k8s/deployment.yaml
        EOF
